# Generated by Django 5.1.6 on 2025-02-26 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('endereco', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=150)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('EMP', 'Empréstimos'), ('CAR', 'Cartão de Crédito'), ('SEG', 'Seguros'), ('SER', 'Serviços'), ('SAU', 'Plano de Saúde')], max_length=3)),
                ('descricao', models.TextField()),
                ('taxa_juros', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('limite_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=150)),
                ('data_admissao', models.DateTimeField(auto_now_add=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.agencia')),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CC', 'Conta corrente'), ('CP', 'Conta poupança')], max_length=2)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.agencia')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEP', 'Depósito'), ('SAQ', 'Saque'), ('PIX', 'Pix'), ('PAG', 'Pagamento')], max_length=3)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.colaborador')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.conta')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.produto')),
            ],
        ),
    ]
